agent: our
bs: 4
bs_val: 4
epochs: 20
exp_id: def
num_workers: 0
only_train: false
peract:
  add_rgc_loss: true
  amp: false
  bnb: false
  lambda_weight_l2: 1.0e-06
  lr: 2.5e-05
  lr_cos_dec: false
  num_rotation_classes: 72
  optimizer_type: lamb
  transform_augmentation: true
  transform_augmentation_rpy:
  - 0.0
  - 0.0
  - 20.0
  transform_augmentation_xyz:
  - 0.1
  - 0.1
  - 0.1
  warmup_steps: 0
peract_official:
  cfg_path: configs/peract_official_config.yaml
resume: ''
rvt:
  gt_hm_sigma: 1.5
  img_aug: 0.1
  move_pc_in_bound: true
  place_with_mean: true
sample_distribution_mode: transition_uniform
tasks: open_drawer
train_iter: 80
val_iter: 32

